// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Person struct {
	ID        sql.NullInt32
	FirstName sql.NullString
	LastName  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
